### ISSUE TITLE
Only fire CD / CI when code changes

### ISSUE THREAD

**Issue by mjarkk** [talpalang/talpa#20]
I find it annoying the CD/CI fires when we haven't even updated any code, it would be nice if it didn't check the MR when there are no code changes.

**Comment by TheOtterlord** [comment]
Could this be what your looking for? [Example ignoring paths](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths)

**Comment by mjarkk** [comment]
Ya i think we are looking for the paths options.

I think this will do the trick:
```yaml
on:
  push:
    branches: [ master ]
    paths:
    - '**.rs'
    - '**.toml'
  pull_request:
    branches: [ master ]
    paths:
    - '**.rs'
    - '**.toml'
```
